In [2]:
#QUESTION 1
#create a class employee.
class Employee:
    #create a datamember to count the no.of employees.
    no_of_employees = 0

    #create a constructor to initialize name,family,salary,department.
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1


    #create a function to average salary.
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
    

#create a fulltime emlpoyee class and it should inherit the properties of Employee class.
class FulltimeEmployee(Employee) :

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("full time employee Benefits.")
    

#create the instances of Fulltime Employee class and employee class and call their member functions.
def main():
    employees = []
    fte1 = FulltimeEmployee("E1", "Family1", 500000, "Developer")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("E2", "Family2", 300000, "Tester")
    employees.append(fte2)
    emp1 = Employee("E3", "Family3", 250000, "HR")
    employees.append(emp1)
    emp2 = Employee("E4", "Family4", 350000, "BA")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()


full time employee Benefits.
Average salary: 350000.0


In [1]:
#QUESTION2 
#create a randomm vector of size 20 having only float in the range 1-20.
import numpy as np
x=np.random.uniform(1,20,20)
print("Original array:")
print(x)
#reshape the array to 4 by 5
x1=x.reshape(4,5)
print("Reshaped Array: ")
print(x1)
#replace the max in each row by 0  (axis=1)
x1[np.arange(len(x1)), x1.argmax(1)]=0
print("Maximum value replaced by 0:")
print(x1)

Original array:
[ 5.67000838 14.49426606 13.45336079 14.61905027 15.74327897  3.01127097
 14.73193385  9.57883816 19.90390434  3.09133785  4.7719876   3.46196796
  1.78184156 10.89122602  2.14378686 13.09680514 19.68951501 16.10465046
 16.42360968 11.42477952]
Reshaped Array: 
[[ 5.67000838 14.49426606 13.45336079 14.61905027 15.74327897]
 [ 3.01127097 14.73193385  9.57883816 19.90390434  3.09133785]
 [ 4.7719876   3.46196796  1.78184156 10.89122602  2.14378686]
 [13.09680514 19.68951501 16.10465046 16.42360968 11.42477952]]
Maximum value replaced by 0:
[[ 5.67000838 14.49426606 13.45336079 14.61905027  0.        ]
 [ 3.01127097 14.73193385  9.57883816  0.          3.09133785]
 [ 4.7719876   3.46196796  1.78184156  0.          2.14378686]
 [13.09680514  0.         16.10465046 16.42360968 11.42477952]]
